# Generated by Django 3.2.11 on 2022-08-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
